export enum Services {
  AUTH_SERVICE = 'AUTH_SERVICE',
  HASHING_SERVICE = 'HASHING_SERVICE',
  USERS_SERVICE = 'USERS_SERVICE',
  JOBS_SERVICE = 'JOBS_SERVICE',
  FILE_MANAGER_SERVICE = 'FILE_MANAGER_SERVICE',
  GATEWAY_SESSION_MANAGER_SERVICE = 'GATEWAY_SESSION_MANAGER_SERVICE',
}

export enum Routes {
  AUTH = 'auth',
  JOBS = 'jobs',
}
